[package]
name = "lottie-data"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Data structures for Lottie animations"

[dependencies]
serde.workspace = true
serde_json.workspace = true
